### ISSUE TITLE
Improper name mapping

### ISSUE THREAD

**Issue by Gaurav2728** [fxn/rails-contributors#63]
@fxn i am contributing in Rails since last year. I checked my name in contributors list but i think it's not proper listed and also reflecting wrong spelling (surname). May be it's releated to one (me @gaurav2728) only but can be happen with others so i created issue

See different scrren shot below for more details

![screen shot 2015-03-16 at 3 54 46 pm](https://cloud.githubusercontent.com/assets/1284716/6664494/32f71108-cbf6-11e4-8cd0-0eb978ce7342.png)
. 
Correct Name is "Gaurav Sharma"

![screen shot 2015-03-16 at 3 55 18 pm](https://cloud.githubusercontent.com/assets/1284716/6664502/45807332-cbf6-11e4-9957-37877f5d53d2.png)
Showing Wrong Name here. ("Gaurav Sharam")
Also commits are not included with my previous rails commit.

![screen shot 2015-03-16 at 3 56 44 pm](https://cloud.githubusercontent.com/assets/1284716/6664517/6c786832-cbf6-11e4-9e3a-1d3cb25a94b7.png)
As name is different that's why it's showing single commit.

![screen shot 2015-03-16 at 3 57 17 pm](https://cloud.githubusercontent.com/assets/1284716/6664648/b045a9b6-cbf7-11e4-8fc6-48da25b2c356.png)

**Comment by rafaelfranca** [comment]
This information was get from the git commit.

```
commit 434c768a7dbf46f7d127d63b825f6eec511b882a
Author: Gaurav Sharam <gaurav2728@gmail.com>
Commit: Gaurav Sharam <gaurav2728@gmail.com>
```

Maybe your configuration was wrong when you did the commit.

**Comment by Gaurav2728** [comment]
@rafaelfranca ok.... Name can be change/update for this commit.

**Comment by fxn** [comment]
Don't worry, the app is ready to fix situations like this. I'm on a trip but will update de credit soon.

**Comment by fxn** [comment]
Could add the correction and deploy from a train (we live in awesome times!), you'll see production is :+1:  now.

**Comment by Gaurav2728** [comment]
@rafaelfranca  @fxn thanks :yellow_heart:  Sounds good app is ready/able to fix that kind of situations. I'll try to do more contributions. Can you tell me some RoR chat room/form where i can/should join and chat or whats new going on so i can keep in touch.

**Comment by fxn** [comment]
@Gaurav2728 There's the [rubyonrails-core](https://groups.google.com/forum/#!forum/rubyonrails-core) mailing list, though the vast majority of work/discussions happen in GitHub PRs or issues. Also there's a weekly newsletter called [This Week in Rails](https://rails-weekly.ongoodbits.com/) with highlights of what is new in the repo and the project to stay current.

Thanks for your interest.
