### ISSUE TITLE
Map users with the same email to one person

### ISSUE THREAD

**Issue by connorshea** [fxn/rails-contributors#78]
My commits are listed as one of two names:

- `Author: connorshea <connor.james.shea@gmail.com>`
- `Author: Connor Shea <connor.james.shea@gmail.com>`

These are listed as separate users but have the same email address. Unless I'm forgetting an edge case, I don't see any reason for these not to be listed under the same user.

We use a fork of this for [GitLab Contributors](http://contributors.gitlab.com), so that's where I noticed it.

Thanks for the awesome app :D

**Comment by fxn** [comment]
This could be a good idea to explore indeed.

I guess it would go like this: if [Commit#extract_candidates](https://github.com/fxn/rails-contributors/blob/95ed0977f2e11e7bbecd650f551ec9518c4bc090/app/models/commit.rb#L87) decides to fallback to the commit author, and the email is already present in the commits table, return the canonical name assigned to that one.

The only gotcha that comes to mind is that a few emails like "carlhuda@engineyard.com" map to two contributors. But these are [known](https://github.com/fxn/rails-contributors/blob/95ed0977f2e11e7bbecd650f551ec9518c4bc090/app/models/names_manager/canonical_names.rb#L60) so maybe we could workaround that.

Would you like to work on it?

**Comment by fxn** [comment]
Actually it might be more complicated. The application does not know which heuristic was applied to the existing commit. For example, the commit could have a hard-coded rule to be associated to someone else, or the commit message could have overriden the author, or the commit could have several authors associated. In those cases this check won't yield a correct association.

**Comment by fxn** [comment]
I have seen more counterexamples.

For example the email "ronnie@dio.jp" has as authors "Akira Matsuda", "Akira Matsuda + Koichi Sasada", "Akira Matsuda & Yukiko Kawamoto", "Akira Matsuda & Kohei Suzuki", "Akira Matsuda & saya", "Akira Matsuda & Naoto Koshikawa". The email "sean@thoughtbot.com" maps to "Sean Griffin", and also "@schneems and @sgrif".

There are quite a few examples of email addresses from which you cannot automatically assign a canonical name.

I think this is trickier that it seems, by now the app is going to keep ignoring emails and work only based on names.

**Comment by connorshea** [comment]
Fair enough, thanks for looking into it.
