### ISSUE TITLE
Some commits are missing in the list

### ISSUE THREAD

**Issue by rafaelfranca** [fxn/rails-contributors#79]
One example of this is @bogdanvlviv. He is not in the list anymore. I could not find a reason for that but seems like this commit is not in the list, or at least it could not get his name.

https://github.com/rails/rails/pull/24327/commits/f2987ceac08c749320f24fd81b1e3f775f145e81

**Comment by rafaelfranca** [comment]
hmmm, the mapping works but Bogdan is not in the list yet

**Comment by fxn** [comment]
This is an edge case in which there is an existing name whose slug matches a new name, by design heuristics try not to be too clever and want to match names exactly. Right now there are 31 comimts without credit (in a total of 68K).

**Comment by rafaelfranca** [comment]
:+1:

**Comment by fxn** [comment]
I pushed the map and closed the issue via the commit message, but production needs to catchup. It's live now http://contributors.rubyonrails.org/contributors/bogdan/commits.

**Comment by bogdanvlviv** [comment]
@fxn, http://contributors.rubyonrails.org/contributors/bogdan/commits, last commit in list isn't my

**Comment by bogdanvlviv** [comment]
i think contributors should be more than 4400, but now 4341.

**Comment by fxn** [comment]
@bogdanvlviv why do you think so.

**Comment by fxn** [comment]
@bogdanvlviv Going to revise the map then, assumed from the description it was yours but we really had two issues to address.

**Comment by bogdanvlviv** [comment]
i know, this commit contributor should be https://github.com/bogdan, http://contributors.rubyonrails.org/contributors/bogdan-gusiev/commits

**Comment by bogdanvlviv** [comment]
i have seen before more than 4400 conributors but now less after https://github.com/rails/rails/commit/8ecc5ab1d88532a239f17c7520ed922c7579b01c i thnik

**Comment by fxn** [comment]
@bogdanvlviv in the last weekend the counter was 4363 exactly, but I researched a bunch of aliases on Monday. And more are going to come. New aliases decrease the counter.

**Comment by fxn** [comment]
New map in production.

**Comment by bogdanvlviv** [comment]
@fxn, why don't make path as http://contributors.rubyonrails.org/contributors/GITHUB_USERNAME/commits for all contributors

**Comment by fxn** [comment]
@bogdanvlviv have a look at the source code of the application and its test suite, this application is not as simple as you might think.

**Comment by bogdanvlviv** [comment]
i will be correctly and less problem. before i have path for my commits http://contributors.rubyonrails.org/contributors/BOGDANVLVIV/commits but now http://contributors.rubyonrails.org/contributors/BOGDAN/commits it is confusing? could i have path with 'bogdanvlviv'?

**Comment by bogdanvlviv** [comment]
i have incorrect start date contribute "19 Jun 2015" should be "26 Mar 2016"

**Comment by fxn** [comment]
Absolutely, that is your choice, if you prefer to appear with your handler the application is able to do it. What do you prefer?

**Comment by fxn** [comment]
(But that means appearing with your handler in the home page as well.)

**Comment by bogdanvlviv** [comment]
i prefer "bogdanvlviv"

**Comment by fxn** [comment]
OK, need to switch tasks now, I'll apply that and check the date later.

**Comment by bogdanvlviv** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
@fxn, thanks!

**Comment by bogdanvlviv** [comment]
@fxn, could you notify me when it will be done?

**Comment by fxn** [comment]
I've seen the problem with the date, the app computes first contribution date for new authors, but if later remaps move commits around, these timestamps are not recomputed.

I am working on both things now.

**Comment by fxn** [comment]
There you go http://contributors.rubyonrails.org/contributors/bogdanvlviv/commits.

The date is also fixed.

**Comment by bogdanvlviv** [comment]
Thanks!
